# Generated by Django 5.0.1 on 2024-05-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_library_returned_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'permissions': [('view_due_books_users', 'Can view due books users')]},
        ),
    ]
