# Generated by Django 5.0.1 on 2024-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_library_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklistmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
